import * as path from 'path';
import { Fixture } from './fixtures';
import { ProbeResult } from './probe';

/** JS literal, not JSON — undefined has to survive. */
function toLiteral(v: unknown, indent = 0): string {
  const pad = '  '.repeat(indent);
  const padIn = '  '.repeat(indent + 1);

  if (v === undefined) return 'undefined';
  if (v === null) return 'null';
  if (typeof v === 'string') return JSON.stringify(v);
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);

  if (Array.isArray(v)) {
    if (v.length === 0) return '[]';
    const items = v.map((x) => `${padIn}${toLiteral(x, indent + 1)}`);
    return `[\n${items.join(',\n')}\n${pad}]`;
  }

  if (typeof v === 'object') {
    const entries = Object.entries(v as Record<string, unknown>);
    if (entries.length === 0) return '{}';
    const items = entries.map(([k, val]) => {
      const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
      return `${padIn}${key}: ${toLiteral(val, indent + 1)}`;
    });
    return `{\n${items.join(',\n')}\n${pad}}`;
  }

  return 'undefined';
}

function importPath(testAbsPath: string, targetAbsPath: string): string {
  let rel = path.relative(path.dirname(testAbsPath), targetAbsPath).replace(/\\/g, '/');
  rel = rel.replace(/\.(tsx?|jsx?)$/, '');
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel;
}

export interface EmitInput {
  testAbsPath: string;
  targetAbsPath: string;
  fixtures: Fixture[];
  results: Map<string, ProbeResult>;
}

export interface EmitOutput {
  contents: string;
  stats: { cases: number; throws: number; skipped: number; functions: string[] };
}

export function emitTestFile(input: EmitInput): EmitOutput {
  const { testAbsPath, targetAbsPath, fixtures, results } = input;

  const byFn = new Map<string, Fixture[]>();
  for (const f of fixtures) {
    const list = byFn.get(f.fnName);
    if (list) list.push(f);
    else byFn.set(f.fnName, [f]);
  }

  let cases = 0;
  let throws = 0;
  let skipped = 0;
  const usedFns: string[] = [];
  const blocks: string[] = [];

  for (const [fnName, fnFixtures] of byFn) {
    const its: string[] = [];
    // Identical (args, outcome) pairs add runtime and kill no extra mutants.
    const seen = new Set<string>();

    for (const f of fnFixtures) {
      const r = results.get(f.id);
      if (!r || r.kind === 'opaque') {
        skipped++;
        continue;
      }

      const argsLiteral = f.args.map((a) => toLiteral(a, 3)).join(', ');
      const dedupeKey = `${argsLiteral}::${r.kind}::${r.literal ?? r.message ?? ''}`;
      if (seen.has(dedupeKey)) {
        skipped++;
        continue;
      }
      seen.add(dedupeKey);

      const title = JSON.stringify(f.label);

      if (r.kind === 'throw') {
        throws++;
        cases++;
        its.push(
          `  it(${title}, () => {\n` +
            `    expect(() => ${fnName}(${argsLiteral})).toThrow(${JSON.stringify(r.message ?? '')});\n` +
            `  });`
        );
        continue;
      }

      cases++;
      // The probe already produced a JS literal from the live value — pasting
      // it verbatim is what keeps Infinity, NaN and undefined intact.
      const expectedLiteral = r.literal ?? 'undefined';
      its.push(
        `  it(${title}, () => {\n` +
          `    expect(${fnName}(${argsLiteral})).toEqual(${expectedLiteral});\n` +
          `  });`
      );
    }

    if (its.length === 0) continue;
    usedFns.push(fnName);
    blocks.push(`describe(${JSON.stringify(fnName)}, () => {\n${its.join('\n\n')}\n});`);
  }

  const imports =
    usedFns.length > 0
      ? `import { ${usedFns.join(', ')} } from '${importPath(testAbsPath, targetAbsPath)}';`
      : '';

  const contents = `/**
 * Generated by rn-qa-engine — built-in generator, no language model involved.
 *
 * These are CHARACTERIZATION tests. Inputs were derived from the type
 * signatures and the numeric constants in the source; expected values are what
 * the code actually returned when run with those inputs.
 *
 * What that means in practice:
 *   - They catch REGRESSIONS: any change that alters behaviour on a covered
 *     input fails here.
 *   - They do NOT verify correctness. If the implementation is wrong today,
 *     these tests pin the wrong behaviour. Read them before merging.
 *
 * Regenerate with:  rnqa feature --project . --apply
 */

${imports}

${blocks.join('\n\n')}
`;

  return { contents, stats: { cases, throws, skipped, functions: usedFns } };
}
