import * as path from 'path';
import { Fixture } from './fixtures';
import { toJsLiteral } from './literal';
import { ProbeResult } from './probe';

function importPath(testAbsPath: string, targetAbsPath: string): string {
  let rel = path.relative(path.dirname(testAbsPath), targetAbsPath).replace(/\\/g, '/');
  rel = rel.replace(/\.(tsx?|jsx?)$/, '');
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel;
}

export interface EmitInput {
  testAbsPath: string;
  targetAbsPath: string;
  fixtures: Fixture[];
  results: Map<string, ProbeResult>;
}

export interface EmitOutput {
  contents: string;
  stats: { cases: number; throws: number; skipped: number; functions: string[] };
}

export function emitTestFile(input: EmitInput): EmitOutput {
  const { testAbsPath, targetAbsPath, fixtures, results } = input;

  const byFn = new Map<string, Fixture[]>();
  for (const f of fixtures) {
    const list = byFn.get(f.fnName);
    if (list) list.push(f);
    else byFn.set(f.fnName, [f]);
  }

  let cases = 0;
  let throws = 0;
  let skipped = 0;
  const usedFns: string[] = [];
  const blocks: string[] = [];

  for (const [fnName, fnFixtures] of byFn) {
    const its: string[] = [];
    // Identical (args, outcome) pairs add runtime and kill no extra mutants.
    const seen = new Set<string>();

    for (const f of fnFixtures) {
      const r = results.get(f.id);
      if (!r || r.kind === 'opaque') {
        skipped++;
        continue;
      }

      // The SAME writer the probe used, so the call in the test is byte-for-byte
      // the call that was actually measured.
      const argLits = f.args.map((a) => toJsLiteral(a));
      if (argLits.some((a) => a === null)) {
        skipped++;
        continue;
      }
      const argsLiteral = argLits.join(', ');
      const dedupeKey = `${argsLiteral}::${r.kind}::${r.literal ?? r.message ?? ''}`;
      if (seen.has(dedupeKey)) {
        skipped++;
        continue;
      }
      seen.add(dedupeKey);

      const title = JSON.stringify(f.label);

      if (r.kind === 'throw') {
        throws++;
        cases++;
        its.push(
          `  it(${title}, () => {\n` +
            `    expect(() => ${fnName}(${argsLiteral})).toThrow(${JSON.stringify(r.message ?? '')});\n` +
            `  });`
        );
        continue;
      }

      cases++;
      // The probe already produced a JS literal from the live value — pasting
      // it verbatim is what keeps Infinity, NaN and undefined intact.
      const expectedLiteral = r.literal ?? 'undefined';
      its.push(
        `  it(${title}, () => {\n` +
          `    expect(${fnName}(${argsLiteral})).toEqual(${expectedLiteral});\n` +
          `  });`
      );
    }

    if (its.length === 0) continue;
    usedFns.push(fnName);
    blocks.push(`describe(${JSON.stringify(fnName)}, () => {\n${its.join('\n\n')}\n});`);
  }

  const imports =
    usedFns.length > 0
      ? `import { ${usedFns.join(', ')} } from '${importPath(testAbsPath, targetAbsPath)}';`
      : '';

  const contents = `/**
 * Generated by rn-qa-engine — built-in generator, no language model involved.
 *
 * These are CHARACTERIZATION tests. Inputs were derived from the type
 * signatures and the numeric constants in the source; expected values are what
 * the code actually returned when run with those inputs.
 *
 * What that means in practice:
 *   - They catch REGRESSIONS: any change that alters behaviour on a covered
 *     input fails here.
 *   - They do NOT verify correctness. If the implementation is wrong today,
 *     these tests pin the wrong behaviour. Read them before merging.
 *
 * Regenerate with:  rnqa feature --project . --apply
 */

${imports}

${blocks.join('\n\n')}
`;

  return { contents, stats: { cases, throws, skipped, functions: usedFns } };
}
