import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { EngineConfig } from '../../types';
import { Sandbox } from '../../verify/sandbox';
import { Fixture } from './fixtures';
import { toJsLiteral } from './literal';

/**
 * Runs the real code with the derived inputs and records what came back.
 *
 * This is the step that lets a generator with no model write a meaningful
 * assertion. It cannot know that the answer *should* be 2500 — but it can
 * observe that it *is* 2500 and pin that, and any mutation which changes the
 * result on a probed input then fails the test.
 *
 * The probe runs through the project's own jest inside a throwaway worktree,
 * so it inherits the repo's transforms, moduleNameMapper and setup mocks, and
 * never touches the developer's tree.
 */

export interface ProbeResult {
  id: string;
  /** 'value' — returned; 'throw' — threw; 'opaque' — not representable as a literal. */
  kind: 'value' | 'throw' | 'opaque';
  /** A JS source literal, ready to paste into the test. NOT JSON. */
  literal?: string;
  message?: string;
  reason?: string;
}

const PROBE_BASENAME = 'rnqa.probe.test.ts';

function probeSource(targetImportPath: string, fixtures: Fixture[], outPath: string): string {
  return `/* generated by rn-qa-engine — probe run, not a real test */
import * as fs from 'fs';
import * as targetModule from '${targetImportPath}';

const OUT_PATH = ${JSON.stringify(outPath)};

const FIXTURES: { id: string; fnName: string; args: unknown[] }[] = [
${fixtures
  .map((f) => {
    const args = f.args.map((a) => toJsLiteral(a));
    if (args.some((a) => a === null)) return null;
    return `  { id: ${JSON.stringify(f.id)}, fnName: ${JSON.stringify(f.fnName)}, args: [${args.join(', ')}] },`;
  })
  .filter((l): l is string => l !== null)
  .join('\n')}
];

/**
 * Serialise to a JS SOURCE LITERAL, not to JSON.
 *
 * JSON cannot represent Infinity, -Infinity, NaN, -0 or undefined — it turns
 * the first three into null and drops the last. A tax slab whose upper bound
 * is Infinity came back as null, and 92 of 187 generated assertions failed
 * against the real value. A round-trip check cannot catch this: null
 * round-trips to null perfectly.
 *
 * JavaScript has literals for all of them, so emit those and skip JSON.
 */
function toLiteral(v: unknown, seen: unknown[] = []): string | null {
  if (v === undefined) return 'undefined';
  if (v === null) return 'null';

  const t = typeof v;
  if (t === 'number') {
    const n = v as number;
    if (Number.isNaN(n)) return 'NaN';
    if (n === Infinity) return 'Infinity';
    if (n === -Infinity) return '-Infinity';
    if (Object.is(n, -0)) return '-0';
    return String(n);
  }
  if (t === 'boolean') return String(v);
  if (t === 'string') return JSON.stringify(v);
  if (t === 'bigint') return String(v) + 'n';
  if (t === 'function' || t === 'symbol') return null;

  if (v instanceof Date) return 'new Date(' + JSON.stringify(v.toISOString()) + ')';
  if (v instanceof RegExp || v instanceof Map || v instanceof Set) return null;

  if (seen.indexOf(v) !== -1) return null; // circular

  if (Array.isArray(v)) {
    const parts: string[] = [];
    for (const item of v) {
      const lit = toLiteral(item, seen.concat([v]));
      if (lit === null) return null;
      parts.push(lit);
    }
    return '[' + parts.join(', ') + ']';
  }

  if (t === 'object') {
    const proto = Object.getPrototypeOf(v);
    // Class instances do not round-trip into an object literal faithfully.
    if (proto !== Object.prototype && proto !== null) return null;
    const parts: string[] = [];
    for (const [k, val] of Object.entries(v as Record<string, unknown>)) {
      const lit = toLiteral(val, seen.concat([v]));
      if (lit === null) return null;
      const key = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k);
      parts.push(key + ': ' + lit);
    }
    return '{' + parts.join(', ') + '}';
  }

  return null;
}

describe('rnqa probe', () => {
  it('captures behaviour for each derived fixture', () => {
    type Outcome =
      | { kind: 'value'; literal: string }
      | { kind: 'throw'; message: string }
      | { kind: 'opaque'; reason: string };

    const callOnce = (f: { fnName: string; args: unknown[] }): Outcome => {
      const fn = (targetModule as Record<string, unknown>)[f.fnName];
      if (typeof fn !== 'function') return { kind: 'opaque', reason: 'export is not a function' };
      try {
        const out = (fn as (...a: unknown[]) => unknown)(...f.args);
        if (out && typeof (out as { then?: unknown }).then === 'function') {
          return { kind: 'opaque', reason: 'returns a promise' };
        }
        const literal = toLiteral(out);
        return literal === null
          ? { kind: 'opaque', reason: 'not representable as a literal' }
          : { kind: 'value', literal };
      } catch (e) {
        return { kind: 'throw', message: String((e as Error)?.message ?? e) };
      }
    };

    // Two passes, with the clock allowed to advance between them.
    //
    // Calling twice back-to-back does NOT detect a function that reads the
    // clock: both calls land inside the same millisecond, so
    // new Date().toISOString() returns the same string and the function looks
    // deterministic. Waiting for the millisecond to tick is what makes the
    // check actually work.
    const first = FIXTURES.map((f) => callOnce(f));

    const startedAt = Date.now();
    while (Date.now() - startedAt < 3) {
      /* busy-wait for the clock to move */
    }

    const second = FIXTURES.map((f) => callOnce(f));

    const results = FIXTURES.map((f, i) => {
      const a = first[i];
      const b = second[i];

      if (a.kind === 'opaque') return { id: f.id, kind: 'opaque', reason: a.reason };
      if (a.kind !== b.kind) {
        return { id: f.id, kind: 'opaque', reason: 'non-deterministic — outcome changed between calls' };
      }
      if (a.kind === 'value' && b.kind === 'value') {
        return a.literal === b.literal
          ? { id: f.id, kind: 'value', literal: a.literal }
          : {
              id: f.id,
              kind: 'opaque',
              reason: 'non-deterministic — two identical calls returned different values',
            };
      }
      if (a.kind === 'throw' && b.kind === 'throw') {
        return a.message === b.message
          ? { id: f.id, kind: 'throw', message: a.message }
          : { id: f.id, kind: 'opaque', reason: 'non-deterministic error message' };
      }
      return { id: f.id, kind: 'opaque', reason: 'unclassifiable' };
    });

    fs.writeFileSync(OUT_PATH, JSON.stringify(results, null, 2));
    expect(results.length).toBe(FIXTURES.length);
  });
});
`;
}

export function runProbe(
  config: EngineConfig,
  targetAbsPath: string,
  fixtures: Fixture[]
): { results: Map<string, ProbeResult>; error: string | null } {
  const sandbox = Sandbox.create(config.projectRoot, 'probe');
  try {
    const targetRel = path.relative(config.projectRoot, targetAbsPath);
    const probeDir = path.dirname(targetRel);
    const probeRel = path.join(probeDir, PROBE_BASENAME);
    const outPath = path.join(sandbox.root, '.rnqa', 'probe.json');
    fs.mkdirSync(path.dirname(outPath), { recursive: true });

    // Import by basename from the same directory — avoids depending on the
    // repo's path aliases resolving inside a generated file.
    const base = './' + path.basename(targetRel).replace(/\.(tsx?|jsx?)$/, '');
    sandbox.writeFile(probeRel, probeSource(base, fixtures, outPath));

    const [bin, ...baseArgs] = config.jest.command.split(/\s+/);
    const args = [
      ...baseArgs,
      '--ci',
      '--silent',
      `--testPathPattern=${PROBE_BASENAME.replace(/\./g, '\\.')}`,
    ];
    if (config.jest.configPath) args.push(`--config=${config.jest.configPath}`);
    if (config.jest.maxWorkers) args.push(`--maxWorkers=${config.jest.maxWorkers}`);

    let stderr = '';
    try {
      execFileSync(bin, args, {
        cwd: sandbox.root,
        stdio: ['ignore', 'pipe', 'pipe'],
        env: { ...process.env, CI: 'true' },
        maxBuffer: 64 * 1024 * 1024,
      });
    } catch (err) {
      const e = err as { stdout?: string; stderr?: string; message?: string };
      stderr = `${e.stdout ?? ''}\n${e.stderr ?? ''}`.split('\n').slice(-25).join('\n');
    }

    if (!fs.existsSync(outPath)) {
      return {
        results: new Map(),
        error: `Probe produced no results. The module may fail to import under jest.\n${stderr}`,
      };
    }

    const raw = JSON.parse(fs.readFileSync(outPath, 'utf8')) as ProbeResult[];
    const map = new Map<string, ProbeResult>();
    for (const r of raw) map.set(r.id, r);
    return { results: map, error: null };
  } finally {
    sandbox.destroy(config.projectRoot);
  }
}
