import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { EngineConfig } from '../../types';
import { Sandbox } from '../../verify/sandbox';
import { Fixture } from './fixtures';

/**
 * Runs the real code with the derived inputs and records what came back.
 *
 * This is the step that lets a generator with no model write a meaningful
 * assertion. It cannot know that the answer *should* be 2500 — but it can
 * observe that it *is* 2500 and pin that, and any mutation which changes the
 * result on a probed input then fails the test.
 *
 * The probe runs through the project's own jest inside a throwaway worktree,
 * so it inherits the repo's transforms, moduleNameMapper and setup mocks, and
 * never touches the developer's tree.
 */

export interface ProbeResult {
  id: string;
  /** 'value' — returned; 'throw' — threw; 'opaque' — not representable as a literal. */
  kind: 'value' | 'throw' | 'opaque';
  value?: unknown;
  message?: string;
  reason?: string;
}

const PROBE_BASENAME = 'rnqa.probe.test.ts';

function probeSource(targetImportPath: string, fixtures: Fixture[], outPath: string): string {
  return `/* generated by rn-qa-engine — probe run, not a real test */
import * as fs from 'fs';
import * as targetModule from '${targetImportPath}';

const FIXTURES: { id: string; fnName: string; args: unknown[] }[] = ${JSON.stringify(
  fixtures.map((f) => ({ id: f.id, fnName: f.fnName, args: f.args }))
)};

/**
 * A value is only usable as an assertion if it can be written back out as a
 * literal. Functions, symbols, class instances, circular structures and
 * anything carrying undefined round-trip badly, so they are recorded as
 * opaque and skipped rather than silently mangled into a wrong expectation.
 */
function represent(v: unknown): { kind: 'value' | 'opaque'; value?: unknown; reason?: string } {
  if (v === undefined) return { kind: 'value', value: null, reason: 'undefined' };
  if (typeof v === 'function' || typeof v === 'symbol') return { kind: 'opaque', reason: typeof v };
  try {
    const json = JSON.stringify(v);
    if (json === undefined) return { kind: 'opaque', reason: 'not serialisable' };
    const round = JSON.parse(json);
    if (JSON.stringify(round) !== json) return { kind: 'opaque', reason: 'unstable round-trip' };
    return { kind: 'value', value: round };
  } catch (e) {
    return { kind: 'opaque', reason: String((e as Error)?.message ?? e) };
  }
}

describe('rnqa probe', () => {
  it('captures behaviour for each derived fixture', () => {
    const results: unknown[] = [];
    for (const f of FIXTURES) {
      const fn = (targetModule as Record<string, unknown>)[f.fnName];
      if (typeof fn !== 'function') {
        results.push({ id: f.id, kind: 'opaque', reason: 'export is not a function' });
        continue;
      }
      try {
        const out = (fn as (...a: unknown[]) => unknown)(...f.args);
        if (out && typeof (out as { then?: unknown }).then === 'function') {
          results.push({ id: f.id, kind: 'opaque', reason: 'returns a promise' });
          continue;
        }
        const r = represent(out);
        results.push(
          r.kind === 'value'
            ? { id: f.id, kind: 'value', value: r.value, reason: r.reason }
            : { id: f.id, kind: 'opaque', reason: r.reason }
        );
      } catch (e) {
        results.push({ id: f.id, kind: 'throw', message: String((e as Error)?.message ?? e) });
      }
    }
    fs.writeFileSync(${JSON.stringify(outPath)}, JSON.stringify(results, null, 2));
    expect(results.length).toBe(FIXTURES.length);
  });
});
`;
}

export function runProbe(
  config: EngineConfig,
  targetAbsPath: string,
  fixtures: Fixture[]
): { results: Map<string, ProbeResult>; error: string | null } {
  const sandbox = Sandbox.create(config.projectRoot, 'probe');
  try {
    const targetRel = path.relative(config.projectRoot, targetAbsPath);
    const probeDir = path.dirname(targetRel);
    const probeRel = path.join(probeDir, PROBE_BASENAME);
    const outPath = path.join(sandbox.root, '.rnqa', 'probe.json');
    fs.mkdirSync(path.dirname(outPath), { recursive: true });

    // Import by basename from the same directory — avoids depending on the
    // repo's path aliases resolving inside a generated file.
    const base = './' + path.basename(targetRel).replace(/\.(tsx?|jsx?)$/, '');
    sandbox.writeFile(probeRel, probeSource(base, fixtures, outPath));

    const [bin, ...baseArgs] = config.jest.command.split(/\s+/);
    const args = [
      ...baseArgs,
      '--ci',
      '--silent',
      `--testPathPattern=${PROBE_BASENAME.replace(/\./g, '\\.')}`,
    ];
    if (config.jest.configPath) args.push(`--config=${config.jest.configPath}`);
    if (config.jest.maxWorkers) args.push(`--maxWorkers=${config.jest.maxWorkers}`);

    let stderr = '';
    try {
      execFileSync(bin, args, {
        cwd: sandbox.root,
        stdio: ['ignore', 'pipe', 'pipe'],
        env: { ...process.env, CI: 'true' },
        maxBuffer: 64 * 1024 * 1024,
      });
    } catch (err) {
      const e = err as { stdout?: string; stderr?: string; message?: string };
      stderr = `${e.stdout ?? ''}\n${e.stderr ?? ''}`.split('\n').slice(-25).join('\n');
    }

    if (!fs.existsSync(outPath)) {
      return {
        results: new Map(),
        error: `Probe produced no results. The module may fail to import under jest.\n${stderr}`,
      };
    }

    const raw = JSON.parse(fs.readFileSync(outPath, 'utf8')) as ProbeResult[];
    const map = new Map<string, ProbeResult>();
    for (const r of raw) map.set(r.id, r);
    return { results: map, error: null };
  } finally {
    sandbox.destroy(config.projectRoot);
  }
}
